# -*- coding: utf-8 -*-
"""proje.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qZOHWg5V9dM8LyyydIICMgKmdKoUfJck
"""

import pandas as pd
import numpy as np

df = pd.read_excel("Dry_Bean_Dataset.xlsx")

for col in ['Area', 'Perimeter']:
    df.loc[df.sample(frac=0.05).index, col] = np.nan

df.to_csv("Dry_Bean_Missing_Example.csv", index=False)

print(df.isnull().sum())

"""# Bölüm 1: Veri Ön İşleme (Preprocessing)"""

df.loc[df.sample(frac=0.35, random_state=42).index, 'MajorAxisLength'] = np.nan

print(df.isnull().sum())

df['Area'].fillna(df['Area'].median(), inplace=True)

df['Perimeter'].fillna(df['Perimeter'].median(), inplace=True)

print(df.isnull().sum())

df.head()

df.drop(columns=["MajorAxisLength"], inplace=True)

# Sütun bazlı silme bu durumda daha mantıklı, çünkü:

# Sadece 1 sütunu kaybederiz

# Diğer tüm özellikler elimizde kalır

# Satır sayısını korumuş oluruz

print(df.isnull().sum().sum())

print(df.head())

print(df.info())

# Sayısal sütunları seçelim (sınıf etiketi hariç)
num_cols = df.select_dtypes(include=['float64', 'int64']).columns
print(num_cols)

Q1 = df[num_cols].quantile(0.25)
Q3 = df[num_cols].quantile(0.75)
IQR = Q3 - Q1

print(IQR)

outliers = ((df[num_cols] < (Q1 - 1.5 * IQR)) | (df[num_cols] > (Q3 + 1.5 * IQR)))

outliers

print(outliers.sum())

# Aykırı değerleri silmemize gerek yok.

# Sınırlandırmaya da gerek yok.

# Aykırı değerler veri setine doğallık katıyor ve modelin genelleme kapasitesine zarar vermez.

"""Neden Özellik Ölçekleme Yapıyoruz?
Makine öğrenmesi algoritmalarının bazıları (özellikle:

Logistic Regression,

KNN,

SVM,

PCA,

LDA) gibi yöntemler, özelliklerin büyüklüklerinden etkilenir.
Örneğin, Area 20.000-30.000 aralığında iken, roundness 0.5-0.9 arasında olabiliyor.
Bu dengesizlik algoritmanın yanlış öğrenmesine neden olabilir.

Ölçekleme yaparak:

Modelin daha hızlı öğrenmesini sağlarız (özellikle gradient descent yöntemlerinde)

Daha doğru sonuçlar alırız

Özellikler eşit ağırlıklı hale gelir (örneğin PCA ve LDA için özellikle önemli!)
"""

from sklearn.preprocessing import StandardScaler

# Sadece sayısal sütunları ölçekleyeceğiz (Class hariç)
num_cols = df.select_dtypes(include=['float64', 'int64']).columns

scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

print(df.head())

"""Veri eksiklerini doldurduk

Aykırı değerleri analiz ettik

Sayısal verileri StandardScaler ile normalize ettik
"""

df["Class"].unique()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Class'] = le.fit_transform(df['Class'])

print(df.head())

print(dict(zip(le.classes_, le.transform(le.classes_))))

"""# Bölüm 2: Özellik Seçimi ve Boyut İndirgeme"""

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import numpy as np

X = df.drop(columns=['Class'])
y = df['Class']

pca = PCA()
X_pca = pca.fit_transform(X)

explained_variance = pca.explained_variance_ratio_
print("Explained Variance Ratios:", explained_variance)
print("Ortalama Explained Variance:", explained_variance.mean())

mean_variance = explained_variance.mean()
selected_components = np.sum(explained_variance > mean_variance)
print("Seçilecek PCA bileşeni sayısı:", selected_components)

plt.figure(figsize=(10, 7))
scatter = plt.scatter(X_pca[:, 0], X_pca[:, 1], c=y, cmap='tab10', alpha=0.7)
plt.title('PCA - İlk İki Bileşen ile Görselleştirme')
plt.xlabel('PCA 1')
plt.ylabel('PCA 2')
plt.colorbar(scatter, label='Class')
plt.grid()
plt.show()

"""Explained Variance Ratios:

[0.525, 0.277, 0.084, 0.054, 0.029, 0.012, ...]

Ortalama: 0.0667



Bu da demek oluyor ki:

1. bileşen: %52.5 varyansı açıklıyor

2. bileşen: %27.7 daha → toplam %80.2 oldu

3. bileşen: %8.4 → toplam %88.6’ya ulaşıyoruz

Ortalama üstünde olan bileşen sayısı = 3

PCA 2D Görselleştirme Yorumu:

Scatter plot’ta class'lar oldukça iyi ayrışmış.

Bazı sınıflar biraz örtüşüyor ama çoğu net gruplar oluşturuyor.

Bu da PCA ile özellik ayrıştırması oldukça başarılı demek.
"""

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
import matplotlib.pyplot as plt

lda = LDA(n_components=3)

X_lda = lda.fit_transform(X, y)

plt.figure(figsize=(10, 7))
scatter = plt.scatter(X_lda[:, 0], X_lda[:, 1], c=y, cmap='tab10', alpha=0.7)
plt.title('LDA - İlk İki Bileşen ile Görselleştirme')
plt.xlabel('LDA 1')
plt.ylabel('LDA 2')
plt.colorbar(scatter, label='Class')
plt.grid()
plt.show()

"""Class 1 (turuncu) örnekleri diğer sınıflardan çok net ayrılmış

Sağ tarafta diğer sınıflar arasında küçük örtüşmeler var ama genel ayrım oldukça başarılı.

Bu da LDA'nın sınıf etiketlerini kullanarak maksimum ayrım gücünü başarıyla uyguladığını gösteriyor.

# Bölüm 3: Modelleme ve Değerlendirme
"""

from sklearn.model_selection import StratifiedKFold, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import numpy as np

X_base = X.copy()
y_base = y.copy()

outer_cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

inner_cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

param_grid = {
    'C': [0.1, 1, 10],
    'solver': ['liblinear']
}

outer_results = {
    'accuracy': [],
    'precision': [],
    'recall': [],
    'f1': []
}

for train_ix, test_ix in outer_cv.split(X_base, y_base):
    X_train, X_test = X_base.iloc[train_ix], X_base.iloc[test_ix]
    y_train, y_test = y_base.iloc[train_ix], y_base.iloc[test_ix]

    model = LogisticRegression()
    clf = GridSearchCV(model, param_grid, cv=inner_cv, scoring='accuracy')
    clf.fit(X_train, y_train)

    best_model = clf.best_estimator_
    y_pred = best_model.predict(X_test)

    outer_results['accuracy'].append(accuracy_score(y_test, y_pred))
    outer_results['precision'].append(precision_score(y_test, y_pred, average='macro'))
    outer_results['recall'].append(recall_score(y_test, y_pred, average='macro'))
    outer_results['f1'].append(f1_score(y_test, y_pred, average='macro'))

for metric in outer_results:
    scores = outer_results[metric]
    print(f"{metric.upper()}: Mean={np.mean(scores):.4f}, Std={np.std(scores):.4f}")

from sklearn.tree import DecisionTreeClassifier

param_grid = {
    'max_depth': [5, 10, 20],
    'criterion': ['gini', 'entropy']
}

outer_results_dt = {
    'accuracy': [],
    'precision': [],
    'recall': [],
    'f1': []
}

for train_ix, test_ix in outer_cv.split(X_base, y_base):
    X_train, X_test = X_base.iloc[train_ix], X_base.iloc[test_ix]
    y_train, y_test = y_base.iloc[train_ix], y_base.iloc[test_ix]

    model = DecisionTreeClassifier(random_state=42)
    clf = GridSearchCV(model, param_grid, cv=inner_cv, scoring='accuracy')
    clf.fit(X_train, y_train)

    best_model = clf.best_estimator_
    y_pred = best_model.predict(X_test)

    outer_results_dt['accuracy'].append(accuracy_score(y_test, y_pred))
    outer_results_dt['precision'].append(precision_score(y_test, y_pred, average='macro'))
    outer_results_dt['recall'].append(recall_score(y_test, y_pred, average='macro'))
    outer_results_dt['f1'].append(f1_score(y_test, y_pred, average='macro'))

for metric in outer_results_dt:
    scores = outer_results_dt[metric]
    print(f"{metric.upper()}: Mean={np.mean(scores):.4f}, Std={np.std(scores):.4f}")

from sklearn.ensemble import RandomForestClassifier

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20, None],
    'criterion': ['gini', 'entropy']
}

outer_results_rf = {
    'accuracy': [],
    'precision': [],
    'recall': [],
    'f1': []
}

for train_ix, test_ix in outer_cv.split(X_base, y_base):
    X_train, X_test = X_base.iloc[train_ix], X_base.iloc[test_ix]
    y_train, y_test = y_base.iloc[train_ix], y_base.iloc[test_ix]

    model = RandomForestClassifier(random_state=42)
    clf = GridSearchCV(model, param_grid, cv=inner_cv, scoring='accuracy')
    clf.fit(X_train, y_train)

    best_model = clf.best_estimator_
    y_pred = best_model.predict(X_test)

    outer_results_rf['accuracy'].append(accuracy_score(y_test, y_pred))
    outer_results_rf['precision'].append(precision_score(y_test, y_pred, average='macro'))
    outer_results_rf['recall'].append(recall_score(y_test, y_pred, average='macro'))
    outer_results_rf['f1'].append(f1_score(y_test, y_pred, average='macro'))

for metric in outer_results_rf:
    scores = outer_results_rf[metric]
    print(f"{metric.upper()}: Mean={np.mean(scores):.4f}, Std={np.std(scores):.4f}")

from warnings import filterwarnings
filterwarnings("ignore")

from xgboost import XGBClassifier

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1]
}

outer_results_xgb = {
    'accuracy': [],
    'precision': [],
    'recall': [],
    'f1': []
}

for train_ix, test_ix in outer_cv.split(X_base, y_base):
    X_train, X_test = X_base.iloc[train_ix], X_base.iloc[test_ix]
    y_train, y_test = y_base.iloc[train_ix], y_base.iloc[test_ix]

    model = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss', random_state=42)
    clf = GridSearchCV(model, param_grid, cv=inner_cv, scoring='accuracy')
    clf.fit(X_train, y_train)

    best_model = clf.best_estimator_
    y_pred = best_model.predict(X_test)

    outer_results_xgb['accuracy'].append(accuracy_score(y_test, y_pred))
    outer_results_xgb['precision'].append(precision_score(y_test, y_pred, average='macro'))
    outer_results_xgb['recall'].append(recall_score(y_test, y_pred, average='macro'))
    outer_results_xgb['f1'].append(f1_score(y_test, y_pred, average='macro'))

for metric in outer_results_xgb:
    scores = outer_results_xgb[metric]
    print(f"{metric.upper()}: Mean={np.mean(scores):.4f}, Std={np.std(scores):.4f}")

from sklearn.naive_bayes import GaussianNB

outer_results_nb = {
    'accuracy': [],
    'precision': [],
    'recall': [],
    'f1': []
}

for train_ix, test_ix in outer_cv.split(X_base, y_base):
    X_train, X_test = X_base.iloc[train_ix], X_base.iloc[test_ix]
    y_train, y_test = y_base.iloc[train_ix], y_base.iloc[test_ix]

    model = GaussianNB()
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    outer_results_nb['accuracy'].append(accuracy_score(y_test, y_pred))
    outer_results_nb['precision'].append(precision_score(y_test, y_pred, average='macro'))
    outer_results_nb['recall'].append(recall_score(y_test, y_pred, average='macro'))
    outer_results_nb['f1'].append(f1_score(y_test, y_pred, average='macro'))

for metric in outer_results_nb:
    scores = outer_results_nb[metric]
    print(f"{metric.upper()}: Mean={np.mean(scores):.4f}, Std={np.std(scores):.4f}")

"""Ham veri üzerinde 5 model için Nested Cross-Validation tamamlandı

Accuracy, Precision, Recall, F1 değerleri hesaplandı
"""

X_pca_final = X_pca[:, :3]

outer_results_pca_lr = {
    'accuracy': [],
    'precision': [],
    'recall': [],
    'f1': []
}

for train_ix, test_ix in outer_cv.split(X_pca_final, y_base):
    X_train, X_test = X_pca_final[train_ix], X_pca_final[test_ix]
    y_train, y_test = y_base.iloc[train_ix], y_base.iloc[test_ix]

    model = LogisticRegression()
    clf = GridSearchCV(model, param_grid={'C': [0.1, 1, 10], 'solver': ['liblinear']}, cv=inner_cv, scoring='accuracy')
    clf.fit(X_train, y_train)

    best_model = clf.best_estimator_
    y_pred = best_model.predict(X_test)

    outer_results_pca_lr['accuracy'].append(accuracy_score(y_test, y_pred))
    outer_results_pca_lr['precision'].append(precision_score(y_test, y_pred, average='macro'))
    outer_results_pca_lr['recall'].append(recall_score(y_test, y_pred, average='macro'))
    outer_results_pca_lr['f1'].append(f1_score(y_test, y_pred, average='macro'))

for metric in outer_results_pca_lr:
    scores = outer_results_pca_lr[metric]
    print(f"{metric.upper()}: Mean={np.mean(scores):.4f}, Std={np.std(scores):.4f}")

# PCA ile boyut indirgediğimiz için doğal olarak performans ham veriye göre düştü.

# Özellikle Recall biraz düştü → bu bazı sınıfları doğru yakalamakta biraz zorluk yaşadığını gösteriyor.

# Fakat yine de %82–%83 doğruluk seviyesi makul.

# PCA ile veri daha kompakt hale geldiği için hesaplama süresi ciddi şekilde azaldı.

X_pca_final = X_pca[:, :3]

outer_results_pca_dt = {
    'accuracy': [],
    'precision': [],
    'recall': [],
    'f1': []
}

for train_ix, test_ix in outer_cv.split(X_pca_final, y_base):
    X_train, X_test = X_pca_final[train_ix], X_pca_final[test_ix]
    y_train, y_test = y_base.iloc[train_ix], y_base.iloc[test_ix]

    model = DecisionTreeClassifier(random_state=42)
    clf = GridSearchCV(model, param_grid={'max_depth': [5, 10, 20], 'criterion': ['gini', 'entropy']}, cv=inner_cv, scoring='accuracy')
    clf.fit(X_train, y_train)

    best_model = clf.best_estimator_
    y_pred = best_model.predict(X_test)

    outer_results_pca_dt['accuracy'].append(accuracy_score(y_test, y_pred))
    outer_results_pca_dt['precision'].append(precision_score(y_test, y_pred, average='macro'))
    outer_results_pca_dt['recall'].append(recall_score(y_test, y_pred, average='macro'))
    outer_results_pca_dt['f1'].append(f1_score(y_test, y_pred, average='macro'))

for metric in outer_results_pca_dt:
    scores = outer_results_pca_dt[metric]
    print(f"{metric.upper()}: Mean={np.mean(scores):.4f}, Std={np.std(scores):.4f}")

"""PCA ile boyut indirgeme sonrası, Decision Tree modeli oldukça başarılı bir performans sergiledi.

Özellikle F1-score ve Recall değerlerinin yüksek olması, modelin sınıfları dengeli bir şekilde ayırt ettiğini gösteriyor.

Bu sonuçlar, PCA'nın Decision Tree ile uyumlu çalıştığını ve verinin önemli bilgilerini koruduğunu gösteriyor.

| Veri Temsili | Model              | Accuracy | F1-score |
|--------------|--------------------|----------|----------|
| Ham Veri     | Logistic Regression | 0.9186   | 0.9316   |
| Ham Veri     | Decision Tree       | 0.9065   | 0.9180   |
| Ham Veri     | Random Forest       | 0.9252   | 0.9363   |
| Ham Veri     | XGBoost             | 0.9287   | 0.9404   |
| Ham Veri     | GaussianNB          | 0.8994   | 0.9092   |
| PCA Verisi   | Logistic Regression | 0.8271   | 0.8126   |
| PCA Verisi   | Decision Tree       | 0.8617   | 0.8614   |
"""

X_pca_final = X_pca[:, :3]

outer_results_pca_rf = {
    'accuracy': [],
    'precision': [],
    'recall': [],
    'f1': []
}

for train_ix, test_ix in outer_cv.split(X_pca_final, y_base):
    X_train, X_test = X_pca_final[train_ix], X_pca_final[test_ix]
    y_train, y_test = y_base.iloc[train_ix], y_base.iloc[test_ix]

    model = RandomForestClassifier(random_state=42)
    clf = GridSearchCV(model, param_grid={
        'n_estimators': [50, 100],
        'max_depth': [5, 10, None]
    }, cv=inner_cv, scoring='accuracy')
    clf.fit(X_train, y_train)

    best_model = clf.best_estimator_
    y_pred = best_model.predict(X_test)

    outer_results_pca_rf['accuracy'].append(accuracy_score(y_test, y_pred))
    outer_results_pca_rf['precision'].append(precision_score(y_test, y_pred, average='macro'))
    outer_results_pca_rf['recall'].append(recall_score(y_test, y_pred, average='macro'))
    outer_results_pca_rf['f1'].append(f1_score(y_test, y_pred, average='macro'))

for metric in outer_results_pca_rf:
    scores = outer_results_pca_rf[metric]
    print(f"{metric.upper()}: Mean={np.mean(scores):.4f}, Std={np.std(scores):.4f}")

"""| Veri Temsili | Model              | Accuracy | F1-score |
|--------------|--------------------|----------|----------|
| Ham Veri     | Logistic Regression | 0.9186   | 0.9316   |
| Ham Veri     | Decision Tree       | 0.9065   | 0.9180   |
| Ham Veri     | Random Forest       | 0.9252   | 0.9363   |
| Ham Veri     | XGBoost             | 0.9287   | 0.9404   |
| Ham Veri     | GaussianNB          | 0.8994   | 0.9092   |
| PCA Verisi   | Logistic Regression | 0.8271   | 0.8126   |
| PCA Verisi   | Decision Tree       | 0.8617   | 0.8614   |
| PCA Verisi   | Random Forest       | 0.8797   | 0.8783   |
"""

X_pca_final = X_pca[:, :3]

outer_results_pca_xgb = {
    'accuracy': [],
    'precision': [],
    'recall': [],
    'f1': []
}

for train_ix, test_ix in outer_cv.split(X_pca_final, y_base):
    X_train, X_test = X_pca_final[train_ix], X_pca_final[test_ix]
    y_train, y_test = y_base.iloc[train_ix], y_base.iloc[test_ix]

    model = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss', random_state=42)
    clf = GridSearchCV(model, param_grid={
        'n_estimators': [100, 200],
        'max_depth': [3, 5, 7],
        'learning_rate': [0.01, 0.1]
    }, cv=inner_cv, scoring='accuracy')
    clf.fit(X_train, y_train)

    best_model = clf.best_estimator_
    y_pred = best_model.predict(X_test)

    outer_results_pca_xgb['accuracy'].append(accuracy_score(y_test, y_pred))
    outer_results_pca_xgb['precision'].append(precision_score(y_test, y_pred, average='macro'))
    outer_results_pca_xgb['recall'].append(recall_score(y_test, y_pred, average='macro'))
    outer_results_pca_xgb['f1'].append(f1_score(y_test, y_pred, average='macro'))

for metric in outer_results_pca_xgb:
    scores = outer_results_pca_xgb[metric]
    print(f"{metric.upper()}: Mean={np.mean(scores):.4f}, Std={np.std(scores):.4f}")

from sklearn.naive_bayes import GaussianNB

X_pca_final = X_pca[:, :3]

outer_results_pca_nb = {
    'accuracy': [],
    'precision': [],
    'recall': [],
    'f1': []
}

for train_ix, test_ix in outer_cv.split(X_pca_final, y_base):
    X_train, X_test = X_pca_final[train_ix], X_pca_final[test_ix]
    y_train, y_test = y_base.iloc[train_ix], y_base.iloc[test_ix]

    model = GaussianNB()
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    outer_results_pca_nb['accuracy'].append(accuracy_score(y_test, y_pred))
    outer_results_pca_nb['precision'].append(precision_score(y_test, y_pred, average='macro'))
    outer_results_pca_nb['recall'].append(recall_score(y_test, y_pred, average='macro'))
    outer_results_pca_nb['f1'].append(f1_score(y_test, y_pred, average='macro'))

for metric in outer_results_pca_nb:
    scores = outer_results_pca_nb[metric]
    print(f"{metric.upper()}: Mean={np.mean(scores):.4f}, Std={np.std(scores):.4f}")

"""| Veri Temsili | Model              | Accuracy | F1-score |
|--------------|--------------------|----------|----------|
| PCA Verisi   | Logistic Regression | 0.8271   | 0.8126   |
| PCA Verisi   | Decision Tree       | 0.8617   | 0.8614   |
| PCA Verisi   | Random Forest       | 0.8797   | 0.8783   |
| PCA Verisi   | XGBoost             | 0.8822   | 0.8800   |
| PCA Verisi   | GaussianNB          | 0.8570   | 0.8577   |
"""

X_lda_final = X_lda

outer_results_lda_lr = {
    'accuracy': [],
    'precision': [],
    'recall': [],
    'f1': []
}

for train_ix, test_ix in outer_cv.split(X_lda_final, y_base):
    X_train, X_test = X_lda_final[train_ix], X_lda_final[test_ix]
    y_train, y_test = y_base.iloc[train_ix], y_base.iloc[test_ix]

    model = LogisticRegression()
    clf = GridSearchCV(model, param_grid={'C': [0.1, 1, 10], 'solver': ['liblinear']}, cv=inner_cv, scoring='accuracy')
    clf.fit(X_train, y_train)

    best_model = clf.best_estimator_
    y_pred = best_model.predict(X_test)

    outer_results_lda_lr['accuracy'].append(accuracy_score(y_test, y_pred))
    outer_results_lda_lr['precision'].append(precision_score(y_test, y_pred, average='macro'))
    outer_results_lda_lr['recall'].append(recall_score(y_test, y_pred, average='macro'))
    outer_results_lda_lr['f1'].append(f1_score(y_test, y_pred, average='macro'))

for metric in outer_results_lda_lr:
    scores = outer_results_lda_lr[metric]
    print(f"{metric.upper()}: Mean={np.mean(scores):.4f}, Std={np.std(scores):.4f}")

"""| Veri Temsili | Model              | Accuracy | F1-score |
|--------------|--------------------|----------|----------|
| LDA Verisi   | Logistic Regression | 0.8591   | 0.8493   |
"""

X_lda_final = X_lda

outer_results_lda_dt = {
    'accuracy': [],
    'precision': [],
    'recall': [],
    'f1': []
}

for train_ix, test_ix in outer_cv.split(X_lda_final, y_base):
    X_train, X_test = X_lda_final[train_ix], X_lda_final[test_ix]
    y_train, y_test = y_base.iloc[train_ix], y_base.iloc[test_ix]

    model = DecisionTreeClassifier(random_state=42)
    clf = GridSearchCV(model, param_grid={'max_depth': [5, 10, 20], 'criterion': ['gini', 'entropy']}, cv=inner_cv, scoring='accuracy')
    clf.fit(X_train, y_train)

    best_model = clf.best_estimator_
    y_pred = best_model.predict(X_test)

    outer_results_lda_dt['accuracy'].append(accuracy_score(y_test, y_pred))
    outer_results_lda_dt['precision'].append(precision_score(y_test, y_pred, average='macro'))
    outer_results_lda_dt['recall'].append(recall_score(y_test, y_pred, average='macro'))
    outer_results_lda_dt['f1'].append(f1_score(y_test, y_pred, average='macro'))

for metric in outer_results_lda_dt:
    scores = outer_results_lda_dt[metric]
    print(f"{metric.upper()}: Mean={np.mean(scores):.4f}, Std={np.std(scores):.4f}")

"""| Veri Temsili | Model              | Accuracy | F1-score |
|--------------|--------------------|----------|----------|
| LDA Verisi   | Logistic Regression | 0.8591   | 0.8493   |
| LDA Verisi   | Decision Tree       | 0.8989   | 0.9116   |
"""

X_lda_final = X_lda

outer_results_lda_rf = {
    'accuracy': [],
    'precision': [],
    'recall': [],
    'f1': []
}

for train_ix, test_ix in outer_cv.split(X_lda_final, y_base):
    X_train, X_test = X_lda_final[train_ix], X_lda_final[test_ix]
    y_train, y_test = y_base.iloc[train_ix], y_base.iloc[test_ix]

    model = RandomForestClassifier(random_state=42)
    clf = GridSearchCV(model, param_grid={
        'n_estimators': [100, 200],
        'max_depth': [10, 20, None],
        'criterion': ['gini', 'entropy']
    }, cv=inner_cv, scoring='accuracy')
    clf.fit(X_train, y_train)

    best_model = clf.best_estimator_
    y_pred = best_model.predict(X_test)

    outer_results_lda_rf['accuracy'].append(accuracy_score(y_test, y_pred))
    outer_results_lda_rf['precision'].append(precision_score(y_test, y_pred, average='macro'))
    outer_results_lda_rf['recall'].append(recall_score(y_test, y_pred, average='macro'))
    outer_results_lda_rf['f1'].append(f1_score(y_test, y_pred, average='macro'))

for metric in outer_results_lda_rf:
    scores = outer_results_lda_rf[metric]
    print(f"{metric.upper()}: Mean={np.mean(scores):.4f}, Std={np.std(scores):.4f}")

from xgboost import XGBClassifier

X_lda_final = X_lda

outer_results_lda_xgb = {
    'accuracy': [],
    'precision': [],
    'recall': [],
    'f1': []
}

for train_ix, test_ix in outer_cv.split(X_lda_final, y_base):
    X_train, X_test = X_lda_final[train_ix], X_lda_final[test_ix]
    y_train, y_test = y_base.iloc[train_ix], y_base.iloc[test_ix]

    model = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss', random_state=42)
    clf = GridSearchCV(model, param_grid={
        'n_estimators': [100, 200],
        'max_depth': [3, 5, 7],
        'learning_rate': [0.01, 0.1]
    }, cv=inner_cv, scoring='accuracy')
    clf.fit(X_train, y_train)

    best_model = clf.best_estimator_
    y_pred = best_model.predict(X_test)

    outer_results_lda_xgb['accuracy'].append(accuracy_score(y_test, y_pred))
    outer_results_lda_xgb['precision'].append(precision_score(y_test, y_pred, average='macro'))
    outer_results_lda_xgb['recall'].append(recall_score(y_test, y_pred, average='macro'))
    outer_results_lda_xgb['f1'].append(f1_score(y_test, y_pred, average='macro'))

for metric in outer_results_lda_xgb:
    scores = outer_results_lda_xgb[metric]
    print(f"{metric.upper()}: Mean={np.mean(scores):.4f}, Std={np.std(scores):.4f}")

from sklearn.naive_bayes import GaussianNB

X_lda_final = X_lda

outer_results_lda_nb = {
    'accuracy': [],
    'precision': [],
    'recall': [],
    'f1': []
}

for train_ix, test_ix in outer_cv.split(X_lda_final, y_base):
    X_train, X_test = X_lda_final[train_ix], X_lda_final[test_ix]
    y_train, y_test = y_base.iloc[train_ix], y_base.iloc[test_ix]

    model = GaussianNB()
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    outer_results_lda_nb['accuracy'].append(accuracy_score(y_test, y_pred))
    outer_results_lda_nb['precision'].append(precision_score(y_test, y_pred, average='macro'))
    outer_results_lda_nb['recall'].append(recall_score(y_test, y_pred, average='macro'))
    outer_results_lda_nb['f1'].append(f1_score(y_test, y_pred, average='macro'))

for metric in outer_results_lda_nb:
    scores = outer_results_lda_nb[metric]
    print(f"{metric.upper()}: Mean={np.mean(scores):.4f}, Std={np.std(scores):.4f}")

"""| Veri Temsili | Model              | Accuracy | F1-score |
|--------------|--------------------|----------|----------|
| LDA Verisi   | Logistic Regression | 0.8591   | 0.8493   |
| LDA Verisi   | Decision Tree       | 0.8989   | 0.9116   |
| LDA Verisi   | Random Forest       | 0.9131   | 0.9250   |
| LDA Verisi   | XGBoost             | 0.9154   | 0.9273   |
| LDA Verisi   | GaussianNB          | 0.8842   | 0.8900   |

| Veri Temsili | Model              | Accuracy | F1-score |
|--------------|--------------------|----------|----------|
| Ham Veri     | Logistic Regression | 0.9186   | 0.9316   |
| Ham Veri     | Decision Tree       | 0.9065   | 0.9180   |
| Ham Veri     | Random Forest       | 0.9252   | 0.9363   |
| Ham Veri     | XGBoost             | 0.9287   | 0.9404   |
| Ham Veri     | GaussianNB          | 0.8994   | 0.9092   |
| PCA Verisi   | Logistic Regression | 0.8271   | 0.8126   |
| PCA Verisi   | Decision Tree       | 0.8617   | 0.8614   |
| PCA Verisi   | Random Forest       | 0.8797   | 0.8783   |
| PCA Verisi   | XGBoost             | 0.8822   | 0.8800   |
| PCA Verisi   | GaussianNB          | 0.8570   | 0.8577   |
| LDA Verisi   | Logistic Regression | 0.8591   | 0.8493   |
| LDA Verisi   | Decision Tree       | 0.8989   | 0.9116   |
| LDA Verisi   | Random Forest       | 0.9131   | 0.9250   |
| LDA Verisi   | XGBoost             | 0.9154   | 0.9273   |
| LDA Verisi   | GaussianNB          | 0.8842   | 0.8900   |

Ham veride XGBoost en iyi modeli verdi.

PCA'da genel başarı düştü ama XGBoost ve Random Forest iyi korudu.

LDA'da XGBoost ve Random Forest yine en iyi sonuçları verdi.

Ham veri kullanılarak elde edilen XGBoost modeli en yüksek doğruluğa ve F1 skoruna ulaşmıştır.
LDA dönüşümü ile XGBoost ve Random Forest modelleri, boyut indirgeme sonrası performansı en az kayıp ile koruyan modeller olmuştur.
"""

from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import numpy as np

# 1. XGBoost en iyi modeli tekrar eğit (final veriyle)
X_train, X_test, y_train, y_test = train_test_split(X_base, y_base, test_size=0.2, stratify=y_base, random_state=42)

best_model = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss', random_state=42,
                           n_estimators=200, max_depth=5, learning_rate=0.1)
best_model.fit(X_train, y_train)

# 2. Gerçek etiketleri binarize et (One-vs-All için)
n_classes = len(np.unique(y_base))
y_test_bin = label_binarize(y_test, classes=np.arange(n_classes))

# 3. Tahmin olasılıkları al
y_score = best_model.predict_proba(X_test)

# 4. ROC eğrilerini çiz
fpr = dict()
tpr = dict()
roc_auc = dict()

for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_test_bin[:, i], y_score[:, i])
    roc_auc[i] = roc_auc_score(y_test_bin[:, i], y_score[:, i])

# 5. Grafik çizimi
plt.figure(figsize=(10, 7))
for i in range(n_classes):
    plt.plot(fpr[i], tpr[i], label=f"Sınıf {i} (AUC = {roc_auc[i]:.2f})")

plt.plot([0, 1], [0, 1], 'k--', label='Rastgele Tahmin')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Eğrileri (XGBoost - Ham Veri)")
plt.legend(loc='lower right')
plt.grid()
plt.show()

"""| Sınıf | AUC Skoru |
|-------|-----------|
| 0     | 0.99      |
| 1     | 1.00      |
| 2     | 1.00      |
| 3     | 0.99      |
| 4     | 1.00      |
| 5     | 1.00      |
| 6     | 0.99      |

Eğrilerin neredeyse tamamı sol üst köşeye çok yakın → model sınıfları çok iyi ayırt edebiliyor.

Rastgele tahmin çizgisi ile eğriler arasındaki fark maksimum ayrım başarısı gösteriyor.

7 sınıfın hepsinde AUC ≥ 0.99 ve bazıları 1.00 → bu, olağanüstü bir genel sınıflandırma performansıdır.
"""

